app:
  name: "HR SAS Backend Service"
  env: development
  cors_origins: http://localhost:3000
  cookie_secure: false
  cookie_domain:

web:
  port: 9000
  prefork: false
log:
  level: 6
database:
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  name: "hr_saas"
  sslmode: "disable"
  timezone: "Asia/Jakarta"
  pool:
    idle: 10
    max: 100
    lifetime: 300

s3:
  endpoint: "https://f25f6724d94ab200c9116b49d8acc632.r2.cloudflarestorage.com" # kosongkan untuk AWS, isi untuk MinIO/Cloudflare R2 (contoh: http://localhost:9000)
  region: "apac"
  bucket: "bw-akses-plus"
  access_key: "453ce78d7559fa4720aa5f164108af0a"
  secret_key: "186829944f018834af8b664642f1f61fea8d1bf4a6dcb26470218341e267cf4c"
  public_url: "https://f25f6724d94ab200c9116b49d8acc632.r2.cloudflarestorage.com/bw-akses-plus" # base URL publik, contoh: https://cdn.example.com atau https://<bucket>.s3.amazonaws.com

face:
  base_url: "http://103.127.133.201:5001"

nasabah:
  base_url: "https://ptkbm.com:8443"
# mail:
#   smtp:
#     host: smtp.gmail.com
#     port: 587
#     username: itbawon@gmail.com
#     password: "ctog pmjh tmff gnsj
#     from: "Bank Wonosobo <itbawon@gmail.com>"
# jwt:
#   secret: "supersecret"
#   issuer: "bw-auth-serice"
#   audience: "bw-users"
#   expires_in: 30000 # menit